name: mockups
description: Supply mockups for third-party libraries
inputs:
  tag:
    description: e.g. win64_vs2017
    required: true
    default: win64_vs2017
runs:
  using: "composite"
  steps:
    - run: |
        curl -OL https://github.com/casadi/mockups/releases/download/v32/mockups_${{ inputs.tag }}.zip
        unzip mockups_${{ inputs.tag }}.zip -d mockups
        ls mockups
        ls mockups/cmake
        echo "MATLAB_ROOT=$GITHUB_WORKSPACE\\mockups" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$GITHUB_WORKSPACE/mockups" >> $GITHUB_ENV
      shell: bash
      
