name: mockups
description: Supply mockups for third-party libraries
inputs:
  tag:
    description: e.g. win64_vs2017
    required: true
    default: win64_vs2017
runs:
  using: "composite"
  steps:
    - run: |
        curl -OL https://github.com/meco-group/mockups/releases/download/v15/mockups_${{ inputs.tag }}.zip
        unzip mockups_${{ inputs.tag }}.zip -d mockups
        ls mockups
        echo "MATLAB_ROOT=$GITHUB_WORKSPACE\\mockups" >> $GITHUB_ENV
      shell: bash
      
