name: mockups
description: Supply mockups for third-party libraries
inputs:
  tag:
    description: e.g. win64_vs2017
    required: true
    default: win64_vs2017
runs:
  using: "composite"
  steps:
    - run: |
        curl -OL https://github.com/meco-group/mockups/releases/download/v3/mockups_${{ inputs.tag }}.zip
        pwd
        ls
        echo $GITHUB_ACTION_PATH
        ls $GITHUB_ACTION_PATH
        unzip mockups_${{ inputs.tag }}.zip $GITHUB_ACTION_PATH/install
        pwd
        ls
        echo "MATLAB_ROOT=$GITHUB_ACTION_PATH/install/matlab" >> $GITHUB_ENV
      shell: bash
      
